package com.ptelive.im.uidemo

import android.content.Context
import android.provider.Settings
import com.ptelive.im.PteIMBaseConfig
import com.ptelive.im.PteIMLanguage
import com.ptelive.im.PteIMResponseCipher
import com.ptelive.im.PteIMThemeMode
import org.json.JSONObject
import android.util.Base64
import java.net.HttpURLConnection
import java.net.URL
import java.util.UUID

/** A server-issued, short-lived credential. It is deliberately kept in memory only. */
internal data class PteIMUIDemoCredential(
  val sdkAppId: Long,
  val userId: Long,
  val userSig: String,
  val expiresAt: Long,
)

internal data class PteIMUIDemoCaptcha(val id: String, val png: ByteArray)
internal data class PteIMUIDemoRegisteredUser(val userId: Long, val nickname: String, val mobile: String)

/**
 * Debug-demo business-login adapter.
 *
 * UserSig is always issued by api-im and decrypted only in process. The demo
 * never contains IM signing keys and never persists the returned signature.
 */
internal class PteIMUIDemoCredentialProvider(
  private val baseConfig: PteIMBaseConfig,
  private val deviceId: String,
) {
  fun captcha(): PteIMUIDemoCaptcha {
    val data = postPublic("/api/v1/demo/auth/captcha", JSONObject())
    val encoded = data.getString("image_data").substringAfter(',')
    return PteIMUIDemoCaptcha(data.getString("captcha_id"), Base64.decode(encoded, Base64.DEFAULT))
  }

  fun login(mobile: String, password: String, captchaId: String, captchaCode: String): PteIMUIDemoCredential =
    authenticate("/api/v1/demo/auth/login", mobile, "", password, captchaId, captchaCode)

  fun register(mobile: String, nickname: String, password: String, captchaId: String, captchaCode: String): PteIMUIDemoCredential =
    authenticate("/api/v1/demo/auth/register", mobile, nickname, password, captchaId, captchaCode)

  /**
   * Local-only convenience entry for visual and integration verification.
   *
   * The identity and UserSig are generated by api-im.  No signing key, static
   * credential or captcha bypass is bundled in the application.
   */
  fun quickLogin(): PteIMUIDemoCredential = credentialFrom(
    postPublic("/api/v1/demo/auth/quick-login", JSONObject().apply {
      put("device_id", deviceId)
      put("platform", "android")
    }),
  )

  fun users(credential: PteIMUIDemoCredential): List<PteIMUIDemoRegisteredUser> {
    val root = encryptedPost("/api/v1/demo/users", JSONObject()) { connection ->
      connection.setRequestProperty("Authorization", "Bearer ${credential.userSig}")
      connection.setRequestProperty("X-Pte-Sdk-AppId", credential.sdkAppId.toString())
      connection.setRequestProperty("X-Pte-User-Id", credential.userId.toString())
    }
    check(root.optInt("code", 0) == 1) { root.optString("msg", "load demo users failed") }
    val list = root.optJSONArray("data") ?: return emptyList()
    return List(list.length()) { index -> list.getJSONObject(index).let { PteIMUIDemoRegisteredUser(it.getString("user_id").toLong(), it.getString("nickname"), it.getString("mobile")) } }
  }

  fun addFriend(credential: PteIMUIDemoCredential, targetUserId: Long) {
    postSdk(credential, "/api/v1/demo/friends/add", JSONObject().put("target_user_id", targetUserId.toString()))
  }

  private fun authenticate(path: String, mobile: String, nickname: String, password: String, captchaId: String, captchaCode: String): PteIMUIDemoCredential {
    val data = postPublic(path, JSONObject().apply {
      put("mobile", mobile)
      if (nickname.isNotBlank()) put("nickname", nickname)
      put("password", password)
      put("captcha_id", captchaId)
      put("captcha_code", captchaCode)
      put("device_id", deviceId)
      put("platform", "android")
    })
    return credentialFrom(data)
  }

  private fun credentialFrom(data: JSONObject): PteIMUIDemoCredential =
    PteIMUIDemoCredential(
      sdkAppId = data.getString("sdk_app_id").toLong(),
      userId = data.getString("user_id").toLong(),
      userSig = data.getString("user_sig"),
      expiresAt = data.optLong("expire_at"),
    )

  private fun postPublic(path: String, payload: JSONObject): JSONObject {
    val root = encryptedPost(path, payload) { connection -> Unit }
    check(root.optInt("code", 0) == 1) { root.optString("msg", "business login failed") }
    return root.optJSONObject("data") ?: error("business login returned no data")
  }

  private fun postSdk(credential: PteIMUIDemoCredential, path: String, payload: JSONObject): JSONObject {
    val root = encryptedPost(path, payload) { connection ->
      connection.setRequestProperty("Authorization", "Bearer ${credential.userSig}")
      connection.setRequestProperty("X-Pte-Sdk-AppId", credential.sdkAppId.toString())
      connection.setRequestProperty("X-Pte-User-Id", credential.userId.toString())
    }
    check(root.optInt("code", 1) == 1) { root.optString("msg", "demo seed request failed") }
    return root.optJSONObject("data") ?: JSONObject()
  }

  private fun encryptedPost(path: String, payload: JSONObject, headers: (HttpURLConnection) -> Unit): JSONObject {
    val responseKey = PteIMResponseCipher.createRequestKey()
    val connection = (URL(baseConfig.apiDomain.trimEnd('/') + path).openConnection() as HttpURLConnection).apply {
      requestMethod = "POST"
      connectTimeout = 10_000
      readTimeout = 10_000
      doOutput = true
      setRequestProperty("Content-Type", "application/json")
      setRequestProperty("X-Pte-Response-Public-Key", PteIMResponseCipher.requestPublicKey(responseKey))
      headers(this)
    }
    return try {
      connection.outputStream.use { output -> output.write(payload.toString().toByteArray(Charsets.UTF_8)) }
      check(connection.responseCode in 200..299) { "demo API request failed with HTTP ${connection.responseCode}" }
      val envelope = JSONObject(connection.inputStream.bufferedReader().use { it.readText() })
      JSONObject(PteIMResponseCipher.decrypt(envelope, responseKey))
    } finally {
      connection.disconnect()
    }
  }
}

/** Stores only non-sensitive demo identity state; UserSig remains memory-only. */
internal class PteIMUIDemoSessionStore(private val context: Context) {
  private val preferences = context.getSharedPreferences("pte_im_ui_demo_session", Context.MODE_PRIVATE)

  fun deviceId(): String = preferences.getString(keyDeviceId, null) ?: stableDeviceId().also {
    preferences.edit().putString(keyDeviceId, it).apply()
  }
  fun markLoggedIn(userId: Long) = preferences.edit().putLong(keyUserId, userId).putBoolean(keyExplicitLogout, false).apply()
  fun markLoggedOut() = preferences.edit().putBoolean(keyExplicitLogout, true).apply()
  fun shouldAutoLoginLocalDemo(): Boolean = !preferences.getBoolean(keyExplicitLogout, false)

  /** Null means the demo keeps using its 07:00–19:00 automatic theme policy. */
  fun manualThemeMode(): PteIMThemeMode? = preferences.getString(keyManualThemeMode, null)?.let { value ->
    runCatching { PteIMThemeMode.valueOf(value) }.getOrNull()
  }
  fun setManualThemeMode(value: PteIMThemeMode) {
    require(value != PteIMThemeMode.SYSTEM) { "Manual theme must be LIGHT or DARK" }
    preferences.edit().putString(keyManualThemeMode, value.name).apply()
  }
  fun clearManualThemeMode() = preferences.edit().remove(keyManualThemeMode).apply()

  /** Null means language follows the Android system locale. */
  fun manualLanguage(): PteIMLanguage? = preferences.getString(keyManualLanguage, null)?.let { value ->
    runCatching { PteIMLanguage.valueOf(value) }.getOrNull()?.takeIf { it != PteIMLanguage.SYSTEM }
  }
  fun setManualLanguage(value: PteIMLanguage?) {
    preferences.edit().apply {
      if (value == null || value == PteIMLanguage.SYSTEM) remove(keyManualLanguage) else putString(keyManualLanguage, value.name)
    }.apply()
  }

  private fun stableDeviceId(): String {
    val androidId = Settings.Secure.getString(context.contentResolver, Settings.Secure.ANDROID_ID)
    return "pte-im-demo-${androidId?.takeIf { it.isNotBlank() } ?: UUID.randomUUID()}"
  }

  companion object {
    private const val keyUserId = "user_id"
    private const val keyDeviceId = "device_id"
    private const val keyExplicitLogout = "explicit_logout"
    private const val keyManualThemeMode = "manual_theme_mode"
    private const val keyManualLanguage = "manual_language"
  }
}
