name: 0️⃣ Priority/Low
about: 优先级低
title: "[Priority/Low]: "
ref: "main"
#assignees:
#  - octocat
labels:
  - Priority/Low

body:
  - type: markdown
    attributes:
      value: '- [ ] 需要处理'

  - type: textarea
    id: describe-issue
    attributes:
      label: 工单内容
      description: '对工单增加项的清晰简洁的描述'
    validations:
      required: true