name: PteIMUIDemo
options:
  bundleIdPrefix: com.ptelive.app.im
  deploymentTarget:
    iOS: '16.0'
packages:
  PteIMSDK:
    path: ../PteIMSDK
  PteIMUIKit:
    path: ../PteIMUIKit
targets:
  PteIMUIDemo:
    type: application
    platform: iOS
    sources: [PteIMUIDemo]
    resources:
      - path: PteIMUIDemo/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ptelive.app.im.sdk.demo
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UILaunchStoryboardName: PteIMUILaunchScreen
        SWIFT_VERSION: '6.0'
        TARGETED_DEVICE_FAMILY: '1,2'
    dependencies:
      - package: PteIMSDK
        product: PteIMSDK
      - package: PteIMUIKit
        product: PteIMUIKit
