name: PteLiveIMDemo
options:
  bundleIdPrefix: com.ptelive.im
  deploymentTarget:
    iOS: '16.0'
packages:
  PteLiveIM:
    path: ../PteLiveIM
  PteIMUIKit:
    path: ../PteIMUIKit
targets:
  PteLiveIMDemo:
    type: application
    platform: iOS
    sources: [PteLiveIMDemo]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ptelive.im.demo
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: '5.9'
        TARGETED_DEVICE_FAMILY: '1,2'
    dependencies:
      - package: PteLiveIM
        product: PteLiveIM
      - package: PteIMUIKit
        product: PteIMUIKit
